name: Update README with a new biology quote

on:
  schedule:
    - cron: "0 0 * * *" # ogni giorno a mezzanotte UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Update README
        run: |
          # Prende una citazione casuale dall'API Quote Garden
          QUOTE_JSON=$(curl -s "https://quote-garden.onrender.com/api/v3/quotes/random?genre=science")
          QUOTE_CONTENT=$(echo $QUOTE_JSON | jq -r '.data[0].quoteText')
          QUOTE_AUTHOR=$(echo $QUOTE_JSON | jq -r '.data[0].quoteAuthor')

          # Se per qualche motivo è vuoto, metti un fallback
          if [ -z "$QUOTE_CONTENT" ] || [ "$QUOTE_CONTENT" = "null" ]; then
            QUOTE_CONTENT="La scienza è organizzata conoscenza."
            QUOTE_AUTHOR="Herbert Spencer"
          fi

          FORMATTED_QUOTE="> *“$QUOTE_CONTENT”*<br>— $QUOTE_AUTHOR"

          # Sostituisce il contenuto tra i marker
          sed -i '/<!--START_BIO_QUOTE-->/, /<!--END_BIO_QUOTE-->/c\<!--START_BIO_QUOTE-->\n'"$FORMATTED_QUOTE"'\n<!--END_BIO_QUOTE-->' README.md

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --staged --quiet || git commit -m "style: ✨ Update daily biology quote"
          git push
