name: Update README with a new biology quote

on:
  schedule:
    - cron: "0 0 * * *" # ogni giorno a mezzanotte UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Update README
        run: |
          # Scarica una citazione casuale dalla Quote Garden API
          QUOTE_JSON=$(curl -s "https://quote-garden.onrender.com/api/v3/quotes/random?genre=science")

          # Controlla se il JSON è valido
          if ! echo "$QUOTE_JSON" | jq . >/dev/null 2>&1; then
            QUOTE_CONTENT="La scienza è organizzata conoscenza."
            QUOTE_AUTHOR="Herbert Spencer"
          else
            QUOTE_CONTENT=$(echo "$QUOTE_JSON" | jq -r '.data[0].quoteText // empty')
            QUOTE_AUTHOR=$(echo "$QUOTE_JSON" | jq -r '.data[0].quoteAuthor // empty')

            # Se i campi sono vuoti, usa il fallback
            if [ -z "$QUOTE_CONTENT" ]; then
              QUOTE_CONTENT="La scienza è organizzata conoscenza."
              QUOTE_AUTHOR="Herbert Spencer"
            fi
          fi

          # Format della citazione in modo sicuro per sed
          FORMATTED_QUOTE=$(printf "> *“%s”*<br>— %s" "$QUOTE_CONTENT" "$QUOTE_AUTHOR")

          # Sostituisce il contenuto tra i marker nel README
          sed -i '/<!--START_BIO_QUOTE-->/, /<!--END_BIO_QUOTE-->/c\<!--START_BIO_QUOTE-->\n'"$FORMATTED_QUOTE"'\n<!--END_BIO_QUOTE-->' README.md
        shell: bash

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --staged --quiet || git commit -m "style: ✨ Update daily biology quote"
          git push
