name: Update README with a new biology quote

on:
  schedule:
    # Esegue l'azione ogni giorno a mezzanotte UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Permette l'esecuzione manuale

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Update README
        run: |
          # Recupera una citazione casuale (tag science o nature)
          QUOTE_JSON=$(curl -s "https://api.quotable.io/random?tags=science|nature")
          QUOTE_CONTENT=$(echo $QUOTE_JSON | jq -r '.content')
          QUOTE_AUTHOR=$(echo $QUOTE_JSON | jq -r '.author')
          FORMATTED_QUOTE="> *“$QUOTE_CONTENT”*<br>— $QUOTE_AUTHOR"

          # Sostituisce il contenuto tra i marker nel README
          sed -i '/<!--START_BIO_QUOTE-->/, /<!--END_BIO_QUOTE-->/c\<!--START_BIO_QUOTE-->\n'"$FORMATTED_QUOTE"'\n<!--END_BIO_QUOTE-->' README.md

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          # Commit solo se ci sono modifiche
          git diff --staged --quiet || git commit -m "style: ✨ Update daily biology quote"
          git push
